### ISSUE TITLE
Inhalte Impressum

### ISSUE THREAD

**Issue by FranziF** [medienherz/in-sneaker#41]
Nachhaken, was genau mit ins Impressum soll (Hinweis GoogleAnalytics, Umsatzsteuernummer…)
Hinweis auf Gestaltung und Programmierung der Seite?
Bzw. legen wir Disclaimer/Datenschutzerklärung und Impressum vllt lieber zusammen? Oder was genau brauchen wir? Sollen die Jungs das noch mal rechtlich checken usw.

**Comment by JanaME** [comment]
Habe jetzt das Impressum eingefügt, soweit erstmal mit Platzhaltern und vor allem mit Ansprechpartner. Falls Matze da was sagt: Ein vollständiger Name ist PFLICHT! Das kann sonst Abmahngebühren von mehreren Tausend Euro kosten. Die Datenschutzerklärung habe ich von Zalando geklaut. Dort ist auch eine Englische, aber da steht ausdrücklich: »We have copyright over this Privacy Policy. Use by third parties – even by way of extract – for commercial purposes is not allowed. Infringements may be subject to legal action.« 
Also habe ich mich das da nicht getraut. Auch bei der Deutschen ist das vielleicht nicht geschickt, bei Zalando zu klauen, aber da steht wenigstens kein Copyright drunter…
Sollen die gucken dann.

**Comment by JanaME** [comment]
Achso und Datenschutzerklärung separat ist auch Pflicht, das darf nicht mit ins Impressum, sondern soll ebenfalls »schnell und eindeutig erreichbar« sein. Neuer Beschluss von Ende 2012 glaub ich.

**Comment by FranziF** [comment]
Oder wir nehmen Inhalte von da http://www.datenschutzerklaerung-online.de/website-online-shop.html und da http://www.datenschutzerklaerung-online.de/datenschutzerklaerung-muster.html – im Kern ist das ja das gleiche wie bei Zalando, nur in Worten, die frei sind :) Oder irgendwie zusammenkopieren. Kein plan. Oder einfach ne Rechtsberatung aufsuchen. Das mit der Zalando-Sache ist schon echt riskant… hmmm

**Comment by FranziF** [comment]
Bei einem Einzelunternehmen muss man doch keinen Geschäftsführer angeben, oder? Das gibt doch nur für GmbHs… Aber oben muss der dann genannt werden. Und §55 gilt doch auch nur wenn man redaktionelle Inhalte zu Verfügung stellt und das ist doch eher nicht so, oder? Würd das einfach wie bei e-Recht machen:

Impressum
Angaben gemäß § 5 TMG:

Max Mustermann -> (das ist dann das einzige Problem was Matze noch klären muss)
Mega Musterladen
Musterstraße 111
Gebäude 44
90210 Musterstadt

Kontakt:
Telefon: +49 (0) 123 44 55 66 (könnte man vllt weglassen…)
mustermann@musterfirma.de

**Comment by JanaME** [comment]
@FranziF  Richtig, aber da die sich bald umfirmieren wollen habe ich das ebenfalls von zalando, ich finde so ist man auf der sicheren Seite und wir müssen nicht ständig alles umändern. Und da wir einige Texte (z.B. Produkttexte bereitstellen) sollte man einen inhaltlichen Verantwortlichen angeben. Falls z.B. Beschwerden wegen falschen Beschreibungen kommen sollten… Das ist bei Shops einfach alles nicht so ohne. Zuviele Abmahngefahren. Daher lieber alles transparent angeben.

**Comment by FranziF** [comment]
Ja hab dir ja die Mails weitergeleitet wie er sich dazu gemeldet hat oder nicht?

**Comment by JanaME** [comment]
Ja ja, sorry hab die gerade erst gelesen. Der ist einfach hohl! Wenn ich sowas lese wie »ist bei Sonic Sales auch immer gut gegangen« dann krieg ich die Pimpanellen oder wie das heißt :D Lass Dich da bloß nicht als Geschäftsführer eintragen, hinterher haftest Du noch für deren Dummheit! ;)
