### ISSUE TITLE
Hinweis auf Vorbestellung

### ISSUE THREAD

**Issue by FranziF** [medienherz/in-sneaker#46]
Hinweis beim Bestellvorgang und auf den Produktunterseiten, dass es sich nur um Vorbestellungen handelt und die Lieferung und Bezahlung erst ab März erfolgt.

**Comment by JanaME** [comment]
Keine Ahnung, wie man das auf Englisch schreibt, aber habs mir mal zurechtgestottert… This is a PREORDER! The shoes will be available on March 2014. You will be informed when payment is required.
:dancers:
