### ISSUE TITLE
Store Locator

### ISSUE THREAD

**Issue by JanaME** [medienherz/in-sneaker#47]
Irgendwie ist der kaputt, da wird nichts angezeigt…
http://www.in-sneaker.com/dealer/

**Comment by FranziF** [comment]
glaub da fehlt der api-key. kümmer ihc mich drum!

**Comment by JanaME** [comment]
Häh? :D Wie kannst Du das denn so schnell wieder heile machen von unterwegs??

**Comment by FranziF** [comment]
Alter ich hab da gar nix dran gemacht. Das ging auf einmal wieder.... strange...
