### ISSUE TITLE
Neue Fotos in Slideshow

### ISSUE THREAD

**Issue by FranziF** [medienherz/in-sneaker#54]
Alle neuen Fotos in den Ordner zur Slideshow kopieren – wenn du mir sagst wo die liegen mach ich das immer nach dem Hochladen direkt!

**Comment by JanaME** [comment]
Die liegen in /wp-content/themes/in-sneaker/images/header-images/shop/
Die heißen die dann so wie das Produkt, weißte?! :))
:dancers:
